### PR TITLE
Enhancement: Scroll to Top, Footer , NextJS top Loader

### LINKED ISSUE #61: Enhancement: Add Scroll to top, Better Hover Animations and NExtjs Top Loader.
Add Scroll to top, Better Hover Animations and NExtjs Top Loader. 
Can improve the UX alot and feels good to eyes

### PR DESCRIPTION
**Pull request by vanshavenger**
Closes #61 
Clean animations on Footer hover, Added scroll to top button, NextjS Top loader for better UX.

### CODE REVIEW

**Comment by Aarzookhunger** [comment]
Can you please attach screenshots of the changes made. In the description, tag the issue which is being closed by this pr.

**Comment by Aarzookhunger** [comment]
Kindly mention issue number under which you were assigned this task, I also need to close it from there.

**Comment by vanshavenger** [comment]
No issues related to it, there are alot of Ui improvements that can be done
and starting with this one, for a better Ui and Ux.

**Comment by Aarzookhunger** [comment]
> No issues related to it, there are alot of Ui improvements that can be done and starting with this one, for a better Ui and Ux

@rahulsainlll can pr directly be merged or we necessarily need to link issue to it (as per gssoc guidelines)?

Also @vanshavenger , the project admin needs to approve (to ensure no one else is working on same) before you raise pr, so in future firstly raise an issue then go ahead with pr.

**Comment by rahulsainlll** [comment]
also this PR has issues bro

**Comment by vanshavenger** [comment]
@rahulsainlll Resolved the conflicts, Review it once.

**Comment by Aarzookhunger** [comment]
For the time being, @vanshavenger open a new issue for the same and I'll assign you that and then you can link it with this PR.

Kindly dont repeat this again, first open issue and then go ahead with pr.

**Comment by vanshavenger** [comment]
@rahulsainlll Obv didn;t do it for gssoc, I just came across the project and thought to Put some little changes. 

@Aarzookhunger on it raising Issue, Will keep that in mind, Thanks :)

**Comment by vanshavenger** [comment]
#61

**Review by Aarzookhunger — APPROVED** [review]

**Comment by vanshavenger** [comment]
@rahulsainlll will do it by weekend, conflicts will happen again and again like this if an approved PR is not merged. The PR was approved a week ago.

Also the whole footer component is changed so ig whole Changes need to be done again to not cause problems to current implementations.

**Pull request closed without merging**
