### PR TITLE
added forgot password backend and frontend

### LINKED ISSUE #21: Addition of forget password functionality (Backend and frontend)
I wanted to add a forget password functionality

Screenshot:
Screenshot 2024-10-02 111905

Currently its missing forget password functionality, making it hard to login once we forget password

**I want to work on this issue.**

under: GSSOC-ext and hacktober

### PR DESCRIPTION
**Pull request by Sourabh782**
Closes #21 

Implemented frontend and backend to forget password
used nodemailer for mailing services

full implementation:
https://github.com/user-attachments/assets/8c3b7b91-67d4-4fa9-9767-08e1f8c2d694

### CODE REVIEW

**Comment by Sourabh782** [comment]
@rahulsainlll can you check it

**Comment by rahulsainlll** [comment]
yeah cool broh good work i will check the code n merge it ASAP. Give me a reminder if i won't merge in two days

**Comment by Sourabh782** [comment]
Sure @rahulsainlll, i would like to req if possible can I get level 3

**Review by Aarzookhunger — APPROVED** [review]

**Comment by Sourabh782** [comment]
Hii Rahul, it's now approved also and been 2 days, can you look into it?

> yeah cool broh good work i will check the code n merge it ASAP. Give me a reminder if i won't merge in two days

**Comment by Sourabh782** [comment]
hello @rahulsainlll any update?

**Comment by Aarzookhunger** [comment]
@rahulsainlll kindly have a look and merge this pr it's been a week!

**Comment by Aarzookhunger** [comment]
@Sourabh782 resolve conflicts please.!

**Comment by Sourabh782** [comment]
@Aarzookhunger done

**Comment by Aarzookhunger** [comment]
> @Aarzookhunger done

Merged and thanks for patience!

**Comment by Sourabh782** [comment]
> > @Aarzookhunger done
> 
> Merged and thanks for patience!

Tq 😊👍

**Pull request merged**
