### PR TITLE
Added the infinite scroll in the issues section of home page

### LINKED ISSUE #100: 📑 Feature Request: Adding infinite scroll to the issues of a repository (see image)
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

So what i want is i want that there will be a infinite scroll feature in the place where all the issues are shown means if the issues are so many then it will not be optimal to load all the issues at a single time.

### Describe your solution to problem

Insted what we should do is that we need to create a infinite scroll in which as the user moves down just before going to the end more issues will load just like in the instagram or other infinite post apps in which list is so long or infinite and it is usefull here because issues of a repo can be so many if it is a large repo and many people are contributing to it.

### Describe alternatives you have considered

_No response_

### Additional context

@rahulsainlll Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add Relevant Screenshot (if available)

image

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# 🚀 Pull Request

## Description

Added the infinite scroll in the issues section of home page

- Fixes #100 
- Closes #100 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/deb6235e-89fc-4fa0-9a93-c50bc96030f9

@rahulsainlll Please check this PR and merge this and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. And label it accordingly it was difficult than i thought it took me 3-4 hours, i did it in 30-45 minutes but then there was a issue then when i scroll down then it is stopped there and continously loading the new issues which shouldn't be there so to fix that thing it took me this much time so please put the level accordingly, it is working perfectly now you can see in the video.

### CODE REVIEW

**Comment by rahulsainlll** [comment]
if someone not assign you that issue you can't do it and if you it anyways you won't get points

**Comment by tarunkumar2005** [comment]
@rahulsainlll please check it I am assigned to this issue.

**Comment by tarunkumar2005** [comment]
Screenshot_20241021_135038_Chrome

**Comment by tarunkumar2005** [comment]
@rahulsainlll check I'm assigned to it.

**Comment by tarunkumar2005** [comment]
@Aarzookhunger @rahulsainlll Resolved conflicts check now.

**Comment by Aarzookhunger** [comment]
@tarunkumar2005 some conflicts are still there.

**Comment by tarunkumar2005** [comment]
@Aarzookhunger Done now there is no issue.

**Review by Aarzookhunger — APPROVED** [review]

**Pull request merged**
