### PR TITLE
New Features & Improvements

### LINKED ISSUE #35: new features
- added style to logout button
- adding about page and to dashboard and removing from footer
- adding redirection links to footer for contribution, issue raising
- adding template & action for RP, issue, bug, documentation update issues and RP template with yaml input component
@rahulsainlll 
do assign i will raise an RP already worked upon and completed the mentioned tasks!

topics
- gssoc-ext 
- hactomberfest

### PR DESCRIPTION
**Pull request by Khushalsarode**
closes #35 
@rahulsainlll @Aarzookhunger do check and let me know!

added about page to dashboard: with redirection to contribution guideline and contribution markdown
footer: added redirection to specific action form footer to raise issue
added PR template
all templates in yaml format with input widgets
added the background and style for logout button instead of text link!

### CODE REVIEW

**Review by Aarzookhunger — CHANGES_REQUESTED** [review]
Can you also add checkbox stating that before raising new feature request, one should ensure that it's not repetitive (already raised issue by someone else), it'll save our time to ensure that we are not assigning same feature to multiple people.!

**Review by Aarzookhunger — APPROVED** [review]

**Review by Aarzookhunger — APPROVED** [review]

**Review by Aarzookhunger — APPROVED** [review]

**Comment by Aarzookhunger** [comment]
Just little change that I suggested above, everything else looks pretty fine!

**Comment by rahulsainlll** [comment]
check the website ig i have merged your PR in the morning this is already done

**Comment by Khushalsarode** [comment]
> check the website ig i have merged your PR in the morning this is already done

so, should i close the request!
but i have done following changes:
git-trace1
git-trace2
git-trace3

**Pull request closed without merging**
