### PR TITLE
Chatbot Added

### LINKED ISSUE #101: 📑 Feature Request: Add chatbot
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

I want to add a AI chatbot for the website

### Describe your solution to problem

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Add Relevant Screenshot (if available)

_No response_

### PR DESCRIPTION
**Pull request by NK-Works**
# 🚀 Pull Request

## Description

Added Chatbot for the website.

- Fixes #101 
- Closes #101

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-22 023427

Code:
image
Update the chatbotid in the above code to activate the chatbot functionality use chatbase.io to create the chatbot id

### CODE REVIEW

**Comment by NK-Works** [comment]
@rahulsainlll any updates on the merge

**Comment by Aarzookhunger** [comment]
@NK-Works does it answer project related queries efficiently? If so, kindly attach screenshots for the same.

**Comment by NK-Works** [comment]
@Aarzookhunger Here you go
image
image

now coming to the main issue regarding the chatbotid without which the website will not work...
You need to create your own chatbot id from https://www.chatbase.co/
I can show u the steps to create and train the chatbot with just putting the website link and the about page as text to the chatbot interface if you want but i can't provide you my personal chatbot id as i dont have a pro account and can only create 1 chatbot at a time...
So for contributing to other repos i need that...
but it just takes 3 mins literally to train you own chatbot in that website using just the link to your website (git-trace) to train the bot... so dont worry and also just message me here I will give u a guide to make your own using screenshots... :)
Hope that works:)

**Comment by Aarzookhunger** [comment]
@rahulsainlll if you can create chatbot I'd from your account, mine is exhausted.

**Comment by NK-Works** [comment]
@rahulsainlll I am facing the same issue...
I have 6 accs 5 are already exhausted while the 6th one is being used to test chatbots for other websites...

**Review by Aarzookhunger — APPROVED** [review]

**Comment by NK-Works** [comment]
@Aarzookhunger now you can merge it

**Comment by Aarzookhunger** [comment]
@NK-Works what about chatbot-id? I approved these changes so that when project admin reviews this it'll be handy for him to merge this PR, but adding I'd for chatbot is still pending.

**Comment by NK-Works** [comment]
@rahulsainlll I have the chatbotid available now as I have created a new account... so if you want I can directly send it in the comments rather than updating the pull req do you want it?

**Pull request merged**
