### PR TITLE
search history added

### LINKED ISSUE #86: 📑 Feature Request: Adding recent searches
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Users often perform repetitive searches for repositories and issues on GitHub, especially when tracking multiple projects or frequently revisiting the same resources. Currently, there is no way to quickly revisit previous searches in Git-trace.

### Describe your solution to problem

Implement a Recent Searches feature that automatically saves and displays the user’s most recent search queries. This would allow users to quickly reuse previous searches without needing to re-enter the search terms manually.

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Add Relevant Screenshot (if available)

_No response_

### PR DESCRIPTION
**Pull request by anishka25**
# 🚀 Pull Request

## Description
In this i have added search history , the history is getting stored in the local storage,of the user. on clicking the recent search the link gets added in the search text box , just click search and you will be good to go.

- Fixes #86
- Closes #(issue Number)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

image

### CODE REVIEW

**Review by Aarzookhunger — APPROVED** [review]

**Comment by anishka25** [comment]
@Aarzookhunger Please merge this PR

**Comment by Aarzookhunger** [comment]
> @Aarzookhunger Please merge this PR

@anishka25 project admin @rahulsainlll will do that! I've approved from my side.

**Comment by rahulsainlll** [comment]
how many history its storing or its ? like is there is any limit

**Comment by rahulsainlll** [comment]
> It shows last 5 searches @rahulsainlll

Ok thanks

**Pull request merged**
