### PR TITLE
Created a static Blog-Page #4

### LINKED ISSUE #4: add static blog section
just to render the markdown its gonna be public no need to login/signup make it clean and concise

### PR DESCRIPTION
**Pull request by ar-rana**
fixes #4 

Changes: 
Added the static blogs page complementing the theme of the website.

how it looks: 
<br/>

image

<br/>
functionaing demo:
<br/>

https://github.com/user-attachments/assets/22265ebf-614c-4e2d-82f6-3d1732c1d63e

### CODE REVIEW

**Comment by rahulsainlll** [comment]
> functionaing demo:
>  Recording.2024-10-01.201056.mp4

can we open those blogs on different page? if no I can make it a level 2 for you if wanna continue

**Comment by ar-rana** [comment]
you want ir such that each blog-card should be able to open a new page, I can do that

**Comment by rahulsainlll** [comment]
> @rahulsainlll if you want it such that each blog-card should be able to open a new page, I can do that, right now they don't open any page

yeah do it

**Comment by ar-rana** [comment]
https://github.com/user-attachments/assets/30a3f5c7-0863-4514-8ed4-33c533cd8d1f

@rahulsainlll I have added the required changes, now each card routes to a separate page

**Comment by rahulsainlll** [comment]
yeah good work broh i will review it asap

**Pull request merged**
