### PR TITLE
Improved  the overall uiux of all the pages keeping it's simplicity.

### PR DESCRIPTION
**Pull request by Adrija05**
# 🚀 Pull Request

## Description

Enhance the home page while maintaining its simplicity and originality. Also, improve the background of the sign-up page, the layout of the 'About Me' page, and modernize the blog page to keep it simple, yet fun and visually engaging.

-Improved the whole uiux and kept it's simplicity.
- Closes #(issue Number)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ yes ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [yes ] My code follows the style guidelines of this project
- [ yes ] I have performed a self-review of my own code
- [ yes ] I have commented my code, particularly in hard-to-understand areas
- [ yes ] I have made corresponding changes to the documentation
- [ yes ] My changes generate no new warnings
- [yes  ] I have added tests that prove my fix is effective or that my feature works
- [ yes ] New and existing unit tests pass locally with my changes
- [ yes ] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
Screenshot 2024-10-15 at 6 13 40 PM

### CODE REVIEW

**Comment by Aarzookhunger** [comment]
@Adrija05 which issue number?

**Comment by Adrija05** [comment]
Issue number #93

**Comment by rahulsainlll** [comment]
could you provide the screen shot of it

**Comment by Adrija05** [comment]
Screenshot 2024-10-16 at 7 26 08 PM
Home page
Screenshot 2024-10-16 at 7 26 15 PM
sign up page
Screenshot 2024-10-16 at 7 26 25 PM
blog page
Screenshot 2024-10-16 at 7 26 32 PM
about page

**Comment by Aarzookhunger** [comment]
> Issue number #93

Not the pr issue number, I'm asking under which issue this has been assigned to you?

**Comment by Adrija05** [comment]
> > Issue number #93
> 
> Not the pr issue number, I'm asking under which issue this has been assigned to you?

I don't understand under which issue means exactly what you want to know but my tags were level 2

**Comment by rahulsainlll** [comment]
> > > Issue number #93
> > 
> > 
> > Not the pr issue number, I'm asking under which issue this has been assigned to you?
> 
> I don't understand under which issue means exactly what you want to know but my tags were level 2

BROH BROH you are not do this you have changed everything 
SORRY to say we can't accept this also where is your issue number? that u provide is pr number

**Comment by Adrija05** [comment]
I don't think 'BROH' is a professional way to communicate. Also, wasn't I supposed to improve the UI/UX? That's exactly what I did by only adjusting the font color and style without adding or removing anything else. 
It's okay if you didn't like it, though.👍

**Pull request closed without merging**
