### PR TITLE
github and google login and sign up

### PR DESCRIPTION
**Pull request by Kartikey2011yadav**
Github SignUp #43
github and google OAuth2 signup support
for the purpose of testing i generated my own secret key and client id for github and google. i added those keys in my .env but for deployment you have to generate those keys. if you don't know how to do so, just let me know i will help you out it's simple 3 min task.

### CODE REVIEW

**Comment by rahulsainlll** [comment]
lol. i do know how to do this i'll merge how to pr ASAP just send me the ss of new design and of npm run build  command also have u updated the schema?

**Comment by Kartikey2011yadav** [comment]
i am using the existing schema the thing is when you attempt to signin with google or github after authentication we get user credential which include mail, name , userId, profile pic, etc. 
there may be times when user is already signed in with credentials(email, password which is currently there), so if he or she attempts to login again with this new functionality i have made it so that if user is already there just sign in if it is not there in data base create a new user with email and the user password will also be email, to resolve such conflicts

**Comment by Kartikey2011yadav** [comment]
241007_10h35m10s_screenshot
241007_10h35m01s_screenshot
241007_10h40m39s_screenshot
241007_10h40m23s_screenshot
this are the current designs

**Comment by Kartikey2011yadav** [comment]
also about access tokens do you use discord if so i can help you with generation of keys it is one time process and takes only 5 min max

**Pull request closed without merging**
