### PR TITLE
Add Copyright Line to Footer

### LINKED ISSUE #171: ⚙ general issue: Add Copyright Line to Footer
### Please describe your feature request related to a problem?

Add a copyright line in the footer section of the website to indicate the ownership and protection of content.

### Describe your solution to problem

- The footer should display a copyright line, such as:
  © 2024 git-trace. All rights reserved.
- The year should update dynamically based on the current year.
- The text should be styled consistently with the rest of the footer content for a cohesive look.

### Describe alternatives you have considered

_No response_

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
# 🚀 Pull Request

## Description

Added a copyright line in the footer section of the website to indicate the ownership and protection of content.

- Fixes #171
- Closes #171 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

image

### CODE REVIEW

**Comment by Aarzookhunger** [comment]
@AnushkaChouhan25 you have hard-coded the year, make it dynamic!

**Review by Aarzookhunger — CHANGES_REQUESTED** [review]
@AnushkaChouhan25 you have hard-coded the year, make it dynamic!

**Comment by Aarzookhunger** [comment]
@AnushkaChouhan25 tomorrow is the last day to merge PR under gssoc, so wrap it up quickly as no merges after 7:00 pm will be counted!

**Comment by AnushkaChouhan25** [comment]
@Aarzookhunger Done

**Review by Aarzookhunger — APPROVED** [review]

**Pull request merged**
