### PR TITLE
Added popular repo section and visualization features

### LINKED ISSUE #92: 📑 Feature Request: Add Popular Repositories Section and Visualization Features
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [x] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Feature 1: Popular Repositories Section

A dedicated section on the homepage that displays trending or popular repositories based on the following criteria:
Stars: Repositories with the most stars.
Forks: Repositories that are widely forked.
Contributions: Repositories with high contributor activity.

Design Details:

Display top 5 or 10 repositories.
Include basic info such as:
Repository name
Owner name
Star count
Fork count
Contribution count
Allow users to view more details or visit the repository directly.

Feature 2: Repository Statistics Visualization

Include visual charts on individual repository pages showing:
Commit History: A timeline or heatmap showing commit activity over time.
Contributor Activity: A bar graph showing the top contributors.
Language Usage: A pie chart or bar chart showing the percentage of different programming languages used.

Tech Stack:

Use Chart.js or D3.js for visualizations.
GitHub API for fetching repository metadata and activity stats.

@rahulsainlll please assign this to me

### Describe your solution to problem

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Add Relevant Screenshot (if available)

_No response_

### PR DESCRIPTION
**Pull request by sezallagwal**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

- Fixes #92 
- Closes #92 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/32222b03-aeef-4c07-b9d6-600c39f6b002

### CODE REVIEW

**Comment by Aarzookhunger** [comment]
@sezallagwal popular based on star count.?

**Comment by sezallagwal** [comment]
@Aarzookhunger @rahulsainlll is this okay or do i need to change anything, you can tell me I will implement that

**Comment by Aarzookhunger** [comment]
@rahulsainlll do you need something like tech wise popular repositories :- for AI , for blockchain , webDev etc. or this general would be okay?

**Comment by rahulsainlll** [comment]
this branch has so many conflicts fix that broh

**Comment by sezallagwal** [comment]
@rahulsainlll fixed it

**Review by Aarzookhunger — APPROVED** [review]

**Pull request merged**
