### PR TITLE
implemented todo functionality #9

### PR DESCRIPTION
**Pull request by ShivanshPlays**
Key Changes:
closes issue #9 
- Schema Update:

Added Todo model with fields for title, description, completed, and bookmarkId.
Seeding:

- Modified the seeding file to add sample todos linked to bookmarks.

- API Routes:

- Created routes for adding, updating, and deleting todos (/api/todos).

- Frontend Integration:

Updated UI to list todos under each bookmark.
Added functionality to add, edit, delete, and mark todos as completed.

This PR adds full todo management to the bookmark system.
Screenshot 2024-10-03 051156
Screenshot 2024-10-03 051219
Screenshot 2024-10-03 051251

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
Hi, do you need any changes?

**Comment by rahulsainlll** [comment]
> Hi, do you need any changes?

rn its look fine does these todo store with along with other issue and bookmark?

**Comment by rahulsainlll** [comment]
> Yeah, I've modified the schema to have another todos table that references bookmark as a foreign key

great i will review this ASAP

**Comment by rahulsainlll** [comment]
just run a npx run build command send me the ss

**Comment by ShivanshPlays** [comment]
Hi @rahulsainlll, humble reminder to merge this PR....

**Comment by rahulsainlll** [comment]
> 
Screenshot 2024-10-04 at 2 38 27 AM




> Hi @rahulsainlll, humble reminder to merge this PR....

see broh I have to check this; do you guyz like as a contributor has a deadline or smth?

**Comment by ShivanshPlays** [comment]
No, actually I was wondering if you have forgotten about it....this will be my first big pr merge, so a little bit excited that's it 😁 

Take your time np

**Comment by rahulsainlll** [comment]
> No, actually I was wondering if you have forgotten about it....this will be my first big pr merge, so a little bit excited that's it 😁
> 
> Take your time np
> 
> Btw I have raised another issue for dockerization, please assign it to me so that I can start working on it while you review

have you made a branch of this PR this one has conflicts you know 
also about the dockerization you can do it in level 3 before the end of gssoc everyone is raising pr might this become conflicts coz they all fork the repo

**Comment by ShivanshPlays** [comment]
Yeah, I forked the repository then 1.I created a new branch named adding_todo 
2.after that I added the to-do features in that branch
3.then I ran npm lint and NPM build just to check if my code was linted correctly 
4. Then I committed my changes in that branch.
5. After that, I pushed the changes to my forked repository.
6. Then I created this pull request.


I don't understand what I have done wrong to cause that merge conflict , I was searching a dev branch in your repository to make pr to, but there was none, so I made a pr to the main branch.


Also, can you please elaborate the docker point I didn't understand it.

**Comment by ShivanshPlays** [comment]
Hi @rahulsainlll , please check I have resolved the merge conflicts....

**Comment by Aarzookhunger** [comment]
> Hi @rahulsainlll , please check I have resolved the merge conflicts....

We need to authorize the deployment so it'll take little time at our end, please wait until then and if any other issue regarding this arises we'll get back to you.

**Review by Puskar-Roy — APPROVED** [review]
Great !

**Comment by ShivanshPlays** [comment]
Hi, this is still not reflecting in the leaderboard please check @Aarzookhunger @Puskar-Roy @sanjay-kv @rahulsainlll

**Comment by rahulsainlll** [comment]
Ig it will take some time else i try to ask the team!

**Pull request merged**
