### PR TITLE
Enhanced the ui design of the login and signup pages.

### LINKED ISSUE #50: Enhancing the login, signup design for better UI/UX and get user a better view on the website
Enhancing the login, signup design for better UI/UX and get user a better view on the website

So i want to enahace the ui ux of the login and signup page just like a professional website so assign this to me under gssoc 2024 ext and hacktoberfect @rahulsainlll

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# 🚀 Pull Request

## Description

Enhanced the ui design of the login and signup pages.

- Fixes #50 
- Closes #50 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
image

image

@rahulsainlll @Aarzookhunger Please check this PR and merge this and assign this to me and put relevant labels such as gssoc 2024 ext and hacktoberfest and level. I have properly enhanced the design keeping in mind the best practices, code efficiency, theme of the website and responsiveness over different screen sizes so i think i deserve a level3 for this.

### CODE REVIEW

**Comment by rahulsainlll** [comment]
is this has the functionality of signup with google?

**Comment by tarunkumar2005** [comment]
@rahulsainlll it doesn't have you said you don't want google auth.

**Comment by Aarzookhunger** [comment]
resolve conflicts @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@Aarzookhunger Solved the issues please check now.

**Review by Aarzookhunger — APPROVED** [review]

**Pull request merged**
