### PR TITLE
added dark  mode toggle

### LINKED ISSUE #41: Dark Mode Toggle for Improved User Experience
Description:
I think it would be great to add a dark mode toggle to our website, allowing users to switch between light and dark themes. Dark mode has become really popular, and giving users this option will make our site more user-friendly.

Why This is Important:
-User Comfort: Dark mode is easier on the eyes, especially in low-light settings.
-Customization: Users can choose their preferred theme based on what they find comfortable.
-Modern Look: It’ll give our site a more modern and professional feel.
-Accessibility: It helps users with visual sensitivities or those who prefer dark mode.

Proposed Solution:
-Add a toggle switch (maybe in the header or settings) to let users switch between light and dark themes.
-Store the user’s choice, so the site remembers their preference when they come back.
-Make sure everything on the site adjusts smoothly to the dark theme, with no issues in readability or functionality.

Design Ideas:
-A simple toggle that switches the theme.
-Could even use fun icons like a sun and moon for the toggle!

Impact:
This will make our site more flexible and appealing to users who like having control over their browsing experience.

I would like to work on this issue and take the responsibility of implementing these changes. Please assign me this issue, and kindly add the respective labels, including the level 3 label.

### PR DESCRIPTION
**Pull request by toufiqfarhan0**
# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

- Fixes #41 
- Closes #41 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/b778b4b5-7e58-4c79-a8a5-fcc131d346c9

### CODE REVIEW

**Comment by toufiqfarhan0** [comment]
@rahulsainlll can you review it?

**Review by Aarzookhunger — CHANGES_REQUESTED** [review]
@toufiqfarhan0 can you make changes to the page as well rather than just changing the background. For example the about and FAQ page.

@rahulsainlll will that be okayy?

**Comment by toufiqfarhan0** [comment]
> @toufiqfarhan0 can you make changes to the page as well rather than just changing the background. For example the about and FAQ page.
> 
> @rahulsainlll will that be okayy?

@Aarzookhunger 

Sure!! You mean those cards right??

**Comment by toufiqfarhan0** [comment]
Screenshot 2024-10-18 163901
Screenshot 2024-10-18 163910
Screenshot 2024-10-18 163917


now @Aarzookhunger @rahulsainlll ???

**Comment by Aarzookhunger** [comment]
@toufiqfarhan0 Looks good now! Thanks for considering the suggestion, the project admin will merge it soon.

**Review by Aarzookhunger — APPROVED** [review]

**Pull request merged**
