### PR TITLE
Design : Added the Contributors page 

### LINKED ISSUE #69: Adding the contributors page to mention all the awersome people who have contributed to the website.
Adding the contributors page to mention all the awersome people who have contributed to the website.

@rahulsainlll Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# 🚀 Pull Request

## Description

Added the Contributors page with super awersome and professional design

## Note
You have to manually go to /contributor page to view this page you can add the link in the navbar for easy access. this is the only thing otherwise the page is i think super amazing.

- Fixes #69 
- Closes #69 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video

https://github.com/user-attachments/assets/b7a8ac46-5c01-4ff9-baef-ec9dd4efe176

@rahulsainlll Check this PR and merge it and assign this to me and put relevent labels like gssoc 2024 ext, hacktoberfest and level, i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.

### CODE REVIEW

**Review by Aarzookhunger — APPROVED** [review]

**Comment by tarunkumar2005** [comment]
@rahulsainlll Please review and merge this and one of the project mentor has already approved so you can quickly review the changes

**Comment by tarunkumar2005** [comment]
@rahulsainlll @Aarzookhunger  Level isn't mentioned in the labels :- i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.

**Comment by tarunkumar2005** [comment]
Can you add the level to it please @Aarzookhunger @rahulsainlll

**Comment by Aarzookhunger** [comment]
@tarunkumar2005 sorry for the delay, Project Admin will label your pr in sometime. You can continue working on some other issue till then.

**Comment by rahulsainlll** [comment]
bhai @tarunkumar2005 you just made the page didn't add somewhere add this in project

**Comment by tarunkumar2005** [comment]
@rahulsainlll I thought links or anything are not needed i can add that and create a new PR or you can simply add a link in the navbar or footer wherever you like and link it to /contributor then it will be fine. you can tell me if you want me to do it too i will create a new PR asp and sorry about this i didn't saw it.

**Pull request merged**
