### PR TITLE
Added auto scrollable testimonial

### LINKED ISSUE #148: 📑 Feature Request: Add testimonial for trust
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Add testimonial page
I can design a beautiful auto scrollable animated testimonial page 

### Describe your solution to problem

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Add Relevant Screenshot (if available)

_No response_

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
# 🚀 Pull Request

 

https://github.com/user-attachments/assets/ee6dc5fc-2ab0-4722-bd59-6abe205f1aa3

- Fixes  #148
- Closes #148

theme oriented testimonial
suitable for both light and dark theme
modular code , you can addd many more testimonial easily 
beautifully design !
# can i get a good level tag for it 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update

## Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Aarzookhunger** [comment]
@Sawan-Kushwah in dark mode, the testimonial option doesn't appear on navbar

**Comment by Sawan-Kushwah** [comment]
image
@Aarzookhunger Done

**Review by Aarzookhunger — APPROVED** [review]

**Comment by Aarzookhunger** [comment]
> @Aarzookhunger its approved but not merged is there something wrong with it ?

The implementation looked fine, it takes time to review code so once I'm done I'll merge.

**Comment by Sawan-Kushwah** [comment]
@Aarzookhunger okay no problem just do it before 31 otherwise i don't get any points for this pr

**Comment by Aarzookhunger** [comment]
> @Aarzookhunger okay no problem just do it before 31 otherwise i don't get any points for this pr

k I'll do it right away.

**Pull request merged**
